### ISSUE TITLE
loginRedirectUrl not working

### ISSUE THREAD

**Issue by kayakwest** [avalanche-canada/ac-web#109]
Current behavior:
1.  I click on Create Report
2.  I am intercepted to login.
3.  I am returned to the avalanche.ca/ route

Desired behavior:
1.  I click on Create Report
2.  I am intercepted to login
3.  I continue to Create Report (/report) route

This was fixed in the MIN v2 release.  https://github.com/tesera/ac-web/commit/c082cafafd4e3c69e38071a0ef2f0dffef7fadf8  Not sure if it was merged.

**Comment by karlguillotte** [comment]
Not relevant anymore.
