### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by kostik-noir** [avalanche-canada/ac-web#40]
https://dl.dropboxusercontent.com/u/2439228/ac-web/controls-of-map-over-menu.ogv
https://dl.dropboxusercontent.com/u/2439228/ac-web/drop-down-menu-visible-in-the-mobile-layout.ogv
https://dl.dropboxusercontent.com/u/2439228/ac-web/invalid-alignment-of-icon.ogv
https://dl.dropboxusercontent.com/u/2439228/ac-web/links-in-mobile-menu-not-works.ogv
https://dl.dropboxusercontent.com/u/2439228/ac-web/mobile-menu-redirect-to-index-page.ogv

**Comment by BenShaw** [comment]
Hi @kostik-noir any chance you have these around still, the dropbox links no longer work

**Comment by kostik-noir** [comment]
Hi @BenShaw 
I will try to restore these files on dropbox

**Comment by BenShaw** [comment]
Thanks !

**Comment by kostik-noir** [comment]
Hi.
Unfortunately I'm not able to restore files. Dropbox store files in the trash during 30 days. I remove these files Feb 23

**Comment by BenShaw** [comment]
no worries @kostik-noir, i think i fixed some of them just not sure i got them all. Thanks anyway
